[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port = 3000
  publish = "public"
  autoLaunch = true
  envFiles = [".env.development"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false

[functions]
  node_bundler = "esbuild" 